name: Deploy Next.js to VPS

on:
  push:
    branches: ["main"]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to VPS
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.PRIVATE_KEY }}
          port: 22
          script: |
            export PATH=$PATH:/www/server/nvm/versions/node/v24.13.0/bin
            cd /www/wwwroot/3hours.io.vn
            git fetch --all
            git reset --hard origin/main
            npm install
            rm -rf .next
            npm run build
            pm2 restart nextjs-app --update-env
            pm2 save
